(load "~/.emacs.d/scarpaz-edit-prefs.el")
(load "~/.emacs.d/scarpaz-calendar.el")
(load "~/.emacs.d/scarpaz-spell-check.el")
(load "~/.emacs.d/scarpaz-user-lookup.el")
(load "~/.emacs.d/scarpaz-key-bindings.el")
(load "~/.emacs.d/scarpaz-battlecruiser.el")
(load "~/.emacs.d/scarpaz-save-hooks.el")
